{
  config,
  pkgs,
  wlib,
  lib,
  ...
}:
let
  inherit (builtins) filter;
  inherit (lib) mkOption literalExpression;
  inherit (lib.types)
    attrsOf
    bool
    enum
    float
    int
    nullOr
    oneOf
    package
    str
    ;

  settingsValueType = oneOf [
    str
    bool
    int
    float
  ];

  tmux-prefix = "ctrl+space";

  yesNo = value: if value then "yes" else "no";

  toKittyConfig = lib.generators.toKeyValue {
    mkKeyValue =
      key: value:
      let
        value' = (if lib.isBool value then yesNo else toString) value;
      in
      "${key} ${value'}";
  };

  toKittyKeybindings = lib.generators.toKeyValue {
    mkKeyValue = key: command: "map ${key} ${command}";
  };
in
{
  imports = [ wlib.modules.default ];

  options = {
    flavour = mkOption {
      type = enum [
        "none"
        "config1"
      ];
      default = "config1";
      description = ''
        Which flavour of configuration to pick:
        - `none`: No configuration, allowed to change
        - `config1`: Not allowed to change.
      '';
    };

    settings = mkOption {
      type = attrsOf settingsValueType;
      default = { };
      example = literalExpression ''
        {
          scrollback_lines = 10000;
          enable_audio_bell = false;
          update_check_interval = 0;
        }
      '';
      description = ''
        See <https://sw.kovidgoyal.net/kitty/conf.html>
        for the documentation.
      '';
    };

    keybindings = mkOption {
      type = attrsOf str;
      default = { };
      description = "Mapping of keybindings to actions.";
      example = literalExpression ''
        {
          "ctrl+c" = "copy_or_interrupt";
          "ctrl+f>2" = "set_font_size 20";
        }
      '';
    };

    font = {
      name = mkOption {
        type = str;
        default = "JetBrains Mono";
        description = "The family name of the font within the package.";
      };

      package = mkOption {
        type = nullOr package;
        default = pkgs.jetbrains-mono;
        description = "Package providing the font.";
      };

      size = mkOption {
        type = int;
        default = 12;
        description = "The size of the font.";
      };
    };
  };

  config = {
    flags = {
      "--config" = config.constructFiles.kittyConfig.path;
    };
    flagSeparator = "=";
    constructFiles = {
      kittyConfig = {
        content = ''
          # Generated by Wrapper
        ''
        + (
          if config.flavour == "none" then
            toKittyConfig config.settings
          else if config.flavour == "config1" then
            toKittyConfig {
              shell_integration = "no-rc";
              background_opacity = 0.85;
              cursor_shape = "block";
              cursor_text_color = "background";
              cursor_trail = 50;
              disable_ligatures = "cursor";
              enabled_layouts = "splits:split_axis=horizontal,stack,tall";
              selection_background = "#fffacd";
              selection_foreground = "#000000";
              symbol_map = "U+e000-U+e00a,U+e0a0-U+e0a2,U+e0b0-U+e0b3,U+e0a3-U+e0a3,U+e0b4-U+e0c8,U+e0cc-U+e0d2,U+e0d4-U+e0d4,U+e0d6-U+e0d7,U+e5fa-U+e6b2,U+e700-U+e7c5,U+f000-U+f2e0,U+e200-U+e2a9,U+f400-U+f4a8,U+2665-U+2665,U+26A1-U+26A1,U+f27c-U+f27c,U+f300-U+f372,U+23fb-U+23fe,U+2b58-U+2b58,U+f0001-U+f0010,U+e300-U+e3eb Symbols Nerd Font";
            }
          else
            null
        )
        + (
          ''

            # Keybindings
          ''
          + (
            if config.flavour == "none" then
              toKittyKeybindings config.keybinds
            else if config.flavour == "config1" then
              toKittyKeybindings {
                "${tmux-prefix}>c" = "new_tab";
                "${tmux-prefix}>n" = "next_tab";
                "${tmux-prefix}>p" = "previous_tab";
                "${tmux-prefix}>," = "set_tab_title";
                "shift+down" = "new_tab";
                "shift+left" = "previous_tab";
                "shift+right" = "next_tab";

                "${tmux-prefix}>|" = "launch --location=vsplit --cwd=current";
                "${tmux-prefix}>%" = "launch --location=vsplit --cwd=current";
                "${tmux-prefix}>-" = "launch --location=hsplit --cwd=current";

                "${tmux-prefix}>h" = "neighboring_window left";
                "${tmux-prefix}>j" = "neighboring_window down";
                "${tmux-prefix}>k" = "neighboring_window up";
                "${tmux-prefix}>l" = "neighboring_window right";
                "ctrl+h" = "neighboring_window left";
                "ctrl+j" = "neighboring_window down";
                "ctrl+k" = "neighboring_window up";
                "ctrl+l" = "neighboring_window right";
                "ctrl+left" = "move_tab_backward";
                "ctrl+right" = "move_tab_forward";

                "${tmux-prefix}>alt+h" = "resize_window narrower";
                "${tmux-prefix}>alt+l" = "resize_window wider";
                "${tmux-prefix}>alt+j" = "resize_window shorter";
                "${tmux-prefix}>alt+k" = "resize_window taller";
                "${tmux-prefix}>shift+h" = "resize_window narrower 3";
                "${tmux-prefix}>shift+l" = "resize_window wider 3";
                "${tmux-prefix}>shift+j" = "resize_window shorter 3";
                "${tmux-prefix}>shift+k" = "resize_window taller 3";
                "${tmux-prefix}>=" = "resize_window reset";

                "${tmux-prefix}>z" = "combine : toggle_layout stack : scroll_prompt_to_bottom";
                "${tmux-prefix}>[" = "show_scrollback";
                "${tmux-prefix}>]" = "paste_from_clipboard";
              }
            else
              null
          )
        )
        + (
          ''

            # Font
          ''
          + (
            if config.flavour == "none" then
              toKittyConfig {
                font_family = config.font.name;
                font_size = config.font.size;
              }
            else if config.flavour == "config1" then
              toKittyConfig {
                font_family = "JetBrains Mono";
                font_size = 12;
              }
            else
              null
          )
        );
        relPath = "kitty.conf";
      };
    };

    extraPackages = filter (pkg: pkg != null) [
      pkgs.jetbrains-mono
      pkgs.nerd-fonts.symbols-only
      config.font.package
    ];

    package = pkgs.kitty;
  };
}
