[pyprland]
plugins = [
	"magnify",
	"scratchpads",
	"shortcuts_menu",
	"toggle_dpms"
]

[pyprland.variables]
TERMINAL = "kitty"
TERMINAL_CLASSED = "kitty --class kitty-dropterm"

[magnify]
duration = 25

[shortcuts_menu.entries]
"Color picker" = [
    {name="format", options=["hex", "rgb", "hsv", "hsl", "cmyk"]},
    "sleep 0.2; hyprpicker --autocopy --format=[format]"
]

screenshot = [
    {name="what", options=["output", "window", "region", "active"]},
    "hyprshot --mode [what] --output-folder /tmp --filename shot_[what].png"
]

annotate = [
    {name="fname", command="ls /tmp/shot_*.png"},
    "satty --filename '[fname]' --output-filename '/tmp/annotated.png'"
]

"Clipboard history" = [
    {name="entry", command="cliphist list", filter="s/\t.*//"},
    "cliphist decode '[entry]' | wl-copy"
]

"Restart waybar" = [
    "pkill waybar && waybar & disown"
]

[scratchpads.term]
animation = "fromTop"
command = "[TERMINAL_CLASSED]"
class = "kitty-dropterm"
size = "75% 70%"
max_size = "1920px 100%"
margin = 50

[scratchpads.volume]
animation = "fromRight"
command = "pavucontrol"
class = "org.pulseaudio.pavucontrol"
size = "40% 90%"
unfocus = "hide"
lazy = true

[scratchpads.nmtui]
animation = "fromRight"
command = "nmtui"
class = "kitty-dropterm"
size = "40% 90%"
unfocus = "hide"
lazy = true

[scratchpads.ncmpcpp]
animation = "fromRight"
command = "[TERMINAL_CLASSED] -e ncmpcpp --slave-screen visualizer"
class = "kitty-dropterm"
size = "90% 65%"
lazy = true

[scratchpads.btop]
animation = "fromBottom"
class = "kitty-dropterm"
command = "[TERMINAL_CLASSED] -e btop"
margin = 50
max_size = "1920px 100%"
size = "95% 70%"
unfocus = "hide"
lazy = true

[scratchpads.htop]
animation = "fromBottom"
class = "kitty-dropterm"
command = "[TERMINAL_CLASSED] -e htop"
margin = 50
max_size = "1920px 100%"
size = "75% 70%"
unfocus = "hide"
lazy = true

[scratchpads.nvtop]
animation = "fromBottom"
class = "kitty-dropterm"
command = "[TERMINAL_CLASSED] -e nvtop"
margin = 50
max_size = "1920px 100%"
size = "75% 70%"
unfocus = "hide"
lazy = true

[scratchpads.yazi]
animation = "fromLeft"
class = "kitty-dropterm"
command = "[TERMINAL_CLASSED] -e yazi"
margin = 50
max_size = "1920px 100%"
size = "75% 85%"

[scratchpads.qalc]
animation = "fromTop"
class = "kitty-dropterm"
command = "[TERMINAL_CLASSED] -e qalc"
margin = 50
max_size = "1920px 100%"
size = "85% 40%"
lazy = true
