[package]
name = "mknix"
version = "0.1.0"
edition = "2024"

[dependencies]
bat = { version = "0.25.0", default-features = false, features = ["minimal-application"] }
clap_complete = "4.5.58"
clap = { version = "4.5.37", features = ["derive"] }
custom_debug = "0.6.2"
rand = "0.9.2"
serde_json = "1.0.142"
serde = { version = "1.0.219", features = ["derive"] }
url = { version = "2.5.4", features = ["serde"] }

[build-dependencies]
clap = { version = "4.5.37", features = ["derive"] }
clap_complete = "4.5.58"
